# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title/

gems: [jekyll-paginate]

# Setup
title:            awans.org
tagline:          '/'
description:      'A BLOG OF SALT, SALT AND FORGETTING'
url:              http://www.awans.org
emblem:           two.png

author:
  name:           'Andrew Wansley'
  url:            https://twitter.com/awans

paginate:         5
exclude:          [ignore]

mini_magick:
  thumbnail:
    source: public/img/original
    destination: public/img/thumbnail
    resize: "100x100"
  medium:
    source: public/img/original
    destination: public/img/medium
    resize: "600x400"
