# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title/

# Setup
title:            awans.org
tagline:          'idk'
description:      'A BLOG OF SALT, SALT AND FORGETTING'
url:              http://www.awans.org
emblem:           astro.png

author:
  name:           'Andrew Wansley'
  url:            https://twitter.com/awans

paginate:         5
exclude:          [ignore]
