baseurl: http://awans.org
disablePathToLower: true
languageCode: en-us
title: Index
theme: salt
pygmentsstyle: dracula
PygmentsCodeFences: true
params:
  sigil: /monstera.png
Permalinks:
  gopkg: "/:filename/"
markup:
  goldmark:
    renderer:
      unsafe: true
